/**
 * GramHealth Digital Triage Engine (js/triage.js)
 * -------------------------------------------------------------
 * Automated Clinical Risk Stratification & Guidance Algorithm
 * 
 * Classifies patient priority into 3 Color-Coded Triage Categories:
 * - RED (Emergency / Severe Risk): Immediate emergency stabilization & CHC/District Hospital referral.
 * - YELLOW (Moderate Risk): Urgent medical review at Primary Health Centre (PHC) within 24 hours.
 * - GREEN (Low Risk / Stable): Routine care, home symptomatic management, or scheduled follow-up.
 * 
 * DISCLAIMER:
 * This triage algorithm provides automated clinical decision assistance for frontline 
 * health workers in rural field settings. It does NOT replace qualified physician assessment.
 */

class TriageEngine {
  constructor() {
    this.DISCLAIMER_TEXT = '⚠️ MEDICAL DISCLAIMER: This triage score is generated by an automated clinical protocol for field guidance only. It does not replace professional medical diagnosis or physician examination.';
  }

  /**
   * Evaluates patient vitals & reported symptoms to determine risk category.
   * 
   * @param {object} vitals - { temp, bpSystolic, bpDiastolic, pulse, spo2, respiratoryRate }
   * @param {Array<string>} symptomsList - Array of symptom strings e.g. ['Chest Pain', 'High Fever']
   * @returns {object} { category, score, redFlags, recommendedActions, disclaimer }
   */
  evaluate(vitals = {}, symptomsList = []) {
    let score = 0;
    const redFlags = [];

    const temp = parseFloat(vitals.temp) || 98.6;
    const bpSys = parseInt(vitals.bpSystolic, 10) || 120;
    const bpDia = parseInt(vitals.bpDiastolic, 10) || 80;
    const pulse = parseInt(vitals.pulse, 10) || 72;
    const spo2 = parseInt(vitals.spo2, 10) || 98;
    const resp = parseInt(vitals.respiratoryRate, 10) || 16;

    // -------------------------------------------------------------
    // 1. EVALUATE CRITICAL VITALS (RED ALERTS)
    // -------------------------------------------------------------
    if (temp >= 103.5) {
      score += 4;
      redFlags.push(`Hyperpyrexia Fever: ${temp}°F`);
    } else if (temp >= 100.4) {
      score += 2;
    }

    if (bpSys >= 180 || bpDia >= 110) {
      score += 5;
      redFlags.push(`Hypertensive Crisis: BP ${bpSys}/${bpDia} mmHg`);
    } else if (bpSys <= 90 || bpDia <= 60) {
      score += 5;
      redFlags.push(`Hypotension / Shock Risk: BP ${bpSys}/${bpDia} mmHg`);
    } else if (bpSys >= 140 || bpDia >= 90) {
      score += 2;
    }

    if (pulse >= 130) {
      score += 4;
      redFlags.push(`Severe Tachycardia: Pulse ${pulse} bpm`);
    } else if (pulse <= 40) {
      score += 4;
      redFlags.push(`Severe Bradycardia: Pulse ${pulse} bpm`);
    } else if (pulse >= 100) {
      score += 2;
    }

    if (spo2 < 90) {
      score += 5;
      redFlags.push(`Severe Hypoxia: SpO2 ${spo2}%`);
    } else if (spo2 < 95) {
      score += 2;
    }

    if (resp >= 30 || resp <= 8) {
      score += 4;
      redFlags.push(`Abnormal Respiratory Rate: ${resp}/min`);
    }

    // -------------------------------------------------------------
    // 2. EVALUATE RED FLAG SYMPTOMS
    // -------------------------------------------------------------
    const criticalSymptoms = [
      'chest pain', 'shortness of breath', 'breathlessness', 'loss of consciousness',
      'unconscious', 'convulsions', 'seizures', 'heavy bleeding', 'severe trauma'
    ];

    symptomsList.forEach(sym => {
      const lower = sym.toLowerCase();
      if (criticalSymptoms.some(crit => lower.includes(crit))) {
        score += 5;
        redFlags.push(`Emergency Symptom: ${sym}`);
      } else {
        score += 1;
      }
    });

    // -------------------------------------------------------------
    // 3. CATEGORIZATION & RECOMMENDED ACTIONS
    // -------------------------------------------------------------
    let category = 'GREEN';
    let recommendedActions = '';

    if (score >= 6 || redFlags.length > 0) {
      category = 'RED';
      recommendedActions = '🚨 HIGH RISK / EMERGENCY: Keep patient rested. Administer oxygen if available. Arrange immediate ambulance dispatch or transfer to District Hospital / CHC. Alert PHC Medical Officer instantly.';
    } else if (score >= 3) {
      category = 'YELLOW';
      recommendedActions = '⚠️ MODERATE RISK: Administer initial symptomatic relief (e.g. Paracetamol for fever, ORS for dehydration). Refer to PHC Doctor within 24 hours. Schedule follow-up visit.';
    } else {
      category = 'GREEN';
      recommendedActions = '🟢 LOW RISK / STABLE: Provide routine preventive advice, home hydration/nutrition guidelines, and issue standard prescription or scheduled follow-up.';
    }

    return {
      category: category,
      score: score,
      redFlags: redFlags,
      recommendedActions: recommendedActions,
      disclaimer: this.DISCLAIMER_TEXT
    };
  }

  /**
   * Helper: Validates whether entered vitals numbers are physiologically possible
   */
  validateVitalsInput(temp, bpSys, bpDia, pulse) {
    const errors = [];
    if (temp && (temp < 93.0 || temp > 109.0)) {
      errors.push('Temperature must be between 93.0°F and 109.0°F');
    }
    if (bpSys && (bpSys < 50 || bpSys > 260)) {
      errors.push('Systolic BP must be between 50 and 260 mmHg');
    }
    if (bpDia && (bpDia < 30 || bpDia > 160)) {
      errors.push('Diastolic BP must be between 30 and 160 mmHg');
    }
    if (pulse && (pulse < 20 || pulse > 240)) {
      errors.push('Pulse must be between 20 and 240 bpm');
    }
    return { isValid: errors.length === 0, errors };
  }
}

// Global Singleton Instance
const triageEngine = new TriageEngine();
